import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/common/Header";
import { Toaster } from "@/components/ui/toaster";
import AppProvider from "@/app/AppProvider";
import { cookies } from "next/headers";
import SlideSession from "@/components/common/SlideSession";
import accountApiRequest from "@/apiRequest/account";
import { AccountResType } from "@/schemaValidations/account.schema";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const cookieStore = cookies()
  const sessionToken = cookieStore.get('sessionToken')


  let user:  AccountResType['data'] | null = null;

  if (sessionToken) {
    const data = await accountApiRequest.me(sessionToken?.value);
    user = data.payload.data;
    console.log("🚀 ~ Header ~ user:", user);
  }
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
      <Toaster />

      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

            <AppProvider initialSessionToken={sessionToken?.value} user={user}>
            <Header/>
            <SlideSession/>

            {children}
            </AppProvider>
           
          </ThemeProvider>
      </body>
    </html>
  );
}
